title: MUHAMMAD AWAIS - Personal Website
description: My Learning Journey

theme: minima   # agar already hai to theek, nahi to add kar do

# Navigation Menu ke liye yeh lines add karo
header_pages:
  - index.md
  - about.md
  - blog.md
  - contact.md
