title: Muhammad Awais - Personal Website
description: My Learning Journey & Experiences

# Important: Yeh line honi chahiye (remote_theme nahi)
theme: minima

# Navigation Menu ke liye
header_pages:
  - index.md
  - about.md
  - blog.md
  - contact.md
